id = "kylejbrk.dbt"
name = "dbt"
schema_version = 1
version = "0.1.0"
authors = ["kylejbrk"]
description = "dbt language support for Zed, powered by dbt-language-server."
repository = "https://github.com/kylejbrk/zed-dbt"

[language_servers.dbt-language-server]
name = "dbt Language Server"
languages = ["SQL", "YAML"]
