name: Release Zed Extension

on:
  push:
    tags:
      - "v*"

jobs:
  homebrew:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/huacnlee/zed-extension-action
      - uses: huacnlee/zed-extension-action@v2
        with:
          extension-name: "dbt"
          push-to: kylejbrk/extensions
        env:
          # the personal access token should have "repo" & "workflow" scopes
          COMMITTER_TOKEN: ${{ secrets.ZED_DBT_RELEASE_TOKEN }}
